feat: Initial implementation of dataset versioning
crocs-muni/sec-certs pull request #370
Opened 2023-10-22 13:08 UTC by GeorgeFI

2023-10-26 07:43 UTC, adamjanovsky commented
I briefly reviewed this and it looks OK. I guess tests need to change as well. We should also add a new test and check if the warning was issued. I'd like to add two types of warnings:

- Just some note in case the release matches and there's some post-version mismatch
- Real warning when the release of the dataset is older than the release of the tool (or vice versa).

2023-10-26 07:44 UTC, adamjanovsky requested changes
I briefly reviewed this and it looks OK. I guess tests need to change as well. We should also add a new test and check if the warning was issued. I'd like to add two types of warnings:

- Just some note in case the release matches and there's some post-version mismatch
- Real warning when the release of the dataset is older than the release of the tool (or vice versa).

2024-01-23 13:02 UTC, J08nY commented
Hey all, what is the status of this? Seems quite stale? A rebase would help.

2025-01-27 15:10 UTC, J08nY commented
Pinging this, @GeorgeFI  @adamjanovsky. Can we get this resolved?

2025-01-27 17:12 UTC, adamjanovsky commented
Not really, no progress there. Unassigning @GeorgeFI as he won't work on this any further.

2025-01-27 17:31 UTC, J08nY commented
Lets either merge or close then. It does not make any sense to keep these three line change here.

Closing.

2025-01-27 17:31 UTC, closed without merging