WiP: Cpe matching
crocs-muni/sec-certs pull request #50
Opened 2021-04-14 15:26 UTC by adamjanovsky

Implements CPE matching code. This involves:
- Class for CPE dataset
- Actual CPE matching
- Some further tests

## What remains to be done

- [ ] Fix encoding error of csv/html resources in tests
- [ ] Add `rapidfuzz` as a dependency into requirements
- [ ] Prepare a function to manually validate the findings of the CPE matching
- [ ] Add relaxed version of matching when no suitable CPE version is found
- [ ] Fine-tune the match threshold
- [ ] Add class for handeling CVE dataset
- [ ] Add functions to correlate CC certificates with CVEs
- [ ] Delete old notebook once done
- [ ] Document the exact matching procedure somewhere
- [ ] Improve parsing of certificate version candidates
- [ ] Compare whether to parse with CPE title or cpe-item field
- [ ] Prefer more general versions

2021-04-15 15:58 UTC, adamjanovsky commented
The CPE matching procedure documented at https://github.com/crocs-muni/sec-certs/wiki/CommonCriteria-certificate-to-CPE-matching-algorithm

2021-04-16 07:25 UTC, adamjanovsky commented
@petrs this might be of an interest to you. There's a function that we will use to manually label candidate CPE matches. It's designed so that it handles most of the stuff automatically to keep the labeling as painless as possible. For each of the certificates you get prompted like this:

```
[0/1] Vendor: NetIQ, Incorporated, Name: NetIQ Access Manager 4.5
	- [0]: CPE(uri='cpe:2.3:a:netiq:access_manager:4.5:sp1:*:*:*:*:*:*', title='NetIQ Access Manager 4.5 Service Pack 1', version='4.5', vendor='netiq', item_name='access manager')
	- [1]: CPE(uri='cpe:2.3:a:netiq:access_manager:4.5:hotfix1:*:*:*:*:*:*', title='NetIQ Access Manager 4.5 Hotfix 1', version='4.5', vendor='netiq', item_name='access manager')
	- [2]: CPE(uri='cpe:2.3:a:netiq:access_manager:4.5:-:*:*:*:*:*:*', title='NetIQ Access Manager 4.5', version='4.5', vendor='netiq', item_name='access manager')
	- [X]: No fitting match
Select fitting CPE matches (split with comma if choosing more):
```

and you are expected to provide input, anything of the following will do:
- `1`
- `1,2,3`
- `1, 2, 3`
- 'X'
- 'asdasdsad' -> Will repeat until you answer :)

The progress is periodically save so that you don't have to label all certificates at once. Only the so-far-unlabeled certificates are of course shown.

2021-04-16 14:52 UTC, adamjanovsky commented
@J08nY not sure how much you feel for the review. The code probably is not perfect, but if you'd manage to point to major problems, that would be nice. 

I think that you at least want to take a look at [examples](https://github.com/crocs-muni/sec-certs/tree/cpe_matching_notebook/examples) (there's also a readme file) and [cpe matching procedure description](https://github.com/crocs-muni/sec-certs/wiki/CommonCriteria-certificate-to-CPE-matching-algorithm) at wiki.

2021-04-16 19:06 UTC, J08nY requested changes
Overall just requested minor changes w.r.t. some configuration handling, naming of functions and the like.

What I would like to see (but is not in scope of this PR, but this PR touched some of the related thing so I bring it up) is that there are not just "examples" using the new codebase but a full replication of the old command-line scripts, such that someone can use the tool without writing any Python code. AFAIK that is a blocker before removing the old codebase (to reach feature parity and have a simple-to-use CLI tool that produces the JSONs).

2021-04-16 19:06 UTC, J08nY commented on sec_certs/dataset.py
> +                        logger.error(f'Bad input from user, repeating instance: {e}')
Is using `logger` to communicate with the user here a good idea? What if `logger` is redirected somewhere? Logs of the library and user printed output do not mix well in this case. I think just prints or perhaps the use of click here is ok.

2021-04-16 19:06 UTC, J08nY commented on sec_certs/dataset.py
> +        logger.info('Retreiving related CVEs to verified CPE matches')
Retr**ei**ving.

2021-04-19 08:47 UTC, adamjanovsky commented on sec_certs/constants.py
> +CPE_MATCHING_THRESHOLD = 70
I agree. Though I'm quite confused with how the config is loaded at the moment. Have to discuss with @mmstanone and do proper config for all parameters of the tool. Will create separate branch/PR for this one.

2021-04-19 09:03 UTC, adamjanovsky commented on sec_certs/cpe.py
> +            reasonable_matches = sorted(reasonable_matches, key=lambda x: x[0], reverse=True)
Nice, did not know this one.

2021-04-19 09:09 UTC, adamjanovsky commented on sec_certs/dataset.py
> +        self.certs: Dict[str, 'CommonCriteriaCert'] = certs  # semantically redundant, but the type hint is needed
[Yep, good tip](https://www.python.org/dev/peps/pep-0526/#class-and-instance-variable-annotations)

2021-04-19 09:14 UTC, adamjanovsky commented on sec_certs/cpe.py
> +        self.vendor_to_versions = {x: list(set(y)) for x, y in self.vendor_to_versions.items()}
Well, I have no idea why didn't I figure that out myself :).

2021-04-19 09:24 UTC, adamjanovsky commented on sec_certs/cpe.py
> +        """
I have the same opinion. Upon new PyCharm install maybe the default docstring style changed and I didn't noticed. Changed it to reStructuredText.

2021-04-19 09:30 UTC, adamjanovsky commented
> Overall just requested minor changes w.r.t. some configuration handling, naming of functions and the like.
> 
> What I would like to see (but is not in scope of this PR, but this PR touched some of the related thing so I bring it up) is that there are not just "examples" using the new codebase but a full replication of the old command-line scripts, such that someone can use the tool without writing any Python code. AFAIK that is a blocker before removing the old codebase (to reach feature parity and have a simple-to-use CLI tool that produces the JSONs).

Apart from minor missing stuff (that you pointed out to me), the `cc_oop_demo.py` is actually the full replication of the code. Takes several hours to run and does all of the following:

1. Download CC data from csv and html
2. Download pdf data related to the parsed certificates
3. Convert all pdfs to txt
4. Analyze keywords in all txts
5. Download CPE dataset and compute candidate CPE matches
6. (expert knowledge) manually label CPE-rich certificates
7. Download CVEDataset
8. Correlate CVEs with CPEs

Once I resolve the missing stuff, we're happy to move the old API to some stale branch.

2021-04-19 09:30 UTC, adamjanovsky commented
@J08nY thanks for pointing to obvious errors. Fixed them all and merging. 🎉

2021-04-19 09:31 UTC, merged